# Controller to attach Gazebo Controller to Moveit! to allow Moveit! to control UR5 in Gazebo.

controller_manager_ns: /
controller_list:
  - name: ur5_1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
